POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "The Second Blog",
    "author": "The Second Author",
    "url": "the.second.url",
    "likes": 1000,
    "userId": "68f65a30c995ca381f9657ce"
}