DELETE http://localhost:3001/api/blogs/68fa5f10b75a151fec70ed4c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4ZjY1YTMwYzk5NWNhMzgxZjk2NTdjZSIsImlhdCI6MTc2MTIzODc4OCwiZXhwIjoxNzYxMjQyMzg4fQ.6MOJ1InmexugFr53bv-dmG_0I4EzDLPtfipE-d0dcQE
Content-Type: application/json